# Generated by Django 5.1 on 2024-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('register_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
