# Generated by Django 5.1 on 2024-08-31 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='achievement_images/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tag', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
