# Generated by Django 5.1 on 2024-08-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='date',
        ),
    ]
