# Generated by Django 5.1 on 2024-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberDeails',
            new_name='MemberDetail',
        ),
    ]
