# Generated by Django 5.1 on 2024-08-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreTeam', '0002_rename_memberdeails_memberdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdetail',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='memberdetail',
            old_name='Instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='memberdetail',
            old_name='LinkedIn',
            new_name='linkedin_url',
        ),
    ]
