# Generated by Django 5.1 on 2024-10-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreTeam', '0003_rename_image_memberdetail_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetail',
            name='image_url',
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='images/CoreTeam'),
        ),
    ]
