# Generated by Django 5.1 on 2024-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreTeam', '0005_memberdetail_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='position',
            field=models.CharField(choices=[('A', 'Coordinator'), ('B', 'Co-coordinator'), ('C', 'Core Team'), ('D', 'Web Development Team')], default='C', max_length=1),
        ),
    ]
