# Generated by Django 5.1 on 2024-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/')),
                ('editor_name', models.CharField(max_length=100)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
