# Generated by Django 5.1 on 2024-08-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_blogs_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
